import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

const translations = {
  en: {
    nav: {
      home: 'Home',
      products: 'Products',
      about: 'About',
      contact: 'Contact',
      allProducts: 'All Products',
      browseByCategory: 'Browse by Category',
      searchProducts: 'Search Products',
      search: 'Search',
      cart: 'Cart',
    },
    footer: {
      navigation: 'Navigation',
      legal: 'Legal',
      followUs: 'Follow Us',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      loading: 'Loading...',
    },
    common: {
      viewDetails: 'View Details',
      buyOnAmazon: 'Buy on Amazon',
      addToCart: 'Add to Cart',
      addedToCart: 'Added to cart',
      quantity: 'Quantity',
      decreaseQuantity: 'Decrease quantity',
      increaseQuantity: 'Increase quantity',
      close: 'Close',
    },
    home: {
      featuredTitle: 'Featured Products',
      featuredSubtitle: 'Discover our carefully curated collection of premium products, each selected for exceptional quality and design.',
      whyChooseTitle: 'Why Choose Your Brand',
      whyChooseSubtitle: "We're redefining the shopping experience with uncompromising quality, innovative design, and customer-first approach.",
      feature1Title: 'Premium Quality',
      feature1Description: 'Every product undergoes rigorous quality testing to ensure it meets our exceptional standards.',
      feature2Title: 'Secure & Trusted',
      feature2Description: 'Advanced security measures protect your data with enterprise-grade encryption and privacy.',
      feature3Title: 'Lightning Fast',
      feature3Description: 'Optimized delivery network ensures your orders arrive quickly and in perfect condition.',
      noFeaturedProducts: 'No featured products available',
      viewAllProducts: 'View All Products',
    },
    products: {
      title: 'Our Products',
      subtitle: 'Discover our carefully curated collection of premium products. Each item is selected for its quality, design, and value.',
      allCategories: 'All Categories',
      apply: 'Apply',
      emptyTitle: 'No products available at the moment.',
      emptySubtitle: 'Please check back later for new arrivals.',
      productImage: 'Product image',
      untitledProduct: 'Untitled Product',
    },
    productDetail: {
      category: 'Category',
      brand: 'Brand',
      upc: 'UPC',
      dateFirstAvailable: 'Date First Available',
      availableOptions: 'Available Options',
      productDescription: 'Product Description',
      customerReviews: 'Customer Reviews',
      onlyReviewsWithImages: 'Only reviews with images',
      sort: 'Sort',
      newest: 'Newest',
      highestRating: 'Highest Rating',
      notFound: 'Product not found',
      backToProducts: 'Back to products',
    },
    cart: {
      title: 'Cart',
      empty: 'Your cart is empty.',
      browseProducts: 'Browse products',
      quantity: 'Quantity',
      options: 'Options',
      remove: 'Remove',
      total: 'Total',
      continueShopping: 'Continue shopping',
      clearCart: 'Clear cart',
    },
    contact: {
      title: 'Contact Us',
      heroText: "Have questions or feedback? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
      sendMessage: 'Send us a Message',
      sendMessageDesc: "Fill out the form below and we'll get back to you as soon as possible.",
      fullName: 'Full Name',
      emailAddress: 'Email Address',
      subject: 'Subject',
      country: 'Country',
      orderNo: 'Order No.',
      message: 'Message',
      sending: 'Sending...',
      send: 'Send Message',
      success: "Thank you for your message! We'll get back to you soon.",
      error: 'There was an error sending your message. Please try again.',
      getInTouch: 'Get in Touch',
      getInTouchDesc: "We're here to help and answer any questions you might have.",
      email: 'Email',
      phone: 'Phone',
      address: 'Address',
      emailRequired: 'Email is required',
      emailInvalid: 'Your email format is incorrect. Please enter a valid email address (e.g., user@example.com)',
    },
    about: {
      title: 'About',
      ourStory: 'Our Story',
      ourMission: 'Our Mission',
      whyChooseUs: 'Why Choose Us',
    },
    privacy: {
      title: 'Privacy Policy',
      intro: 'Learn how we collect, use, and protect your data.',
      overview: 'Overview',
      dataWeCollect: 'Data We Collect',
      yourRights: 'Your Rights',
      contact: 'Contact',
      dataWeCollectItems: [
        'Account information such as name and email.',
        'Order and payment details processed securely.',
        'Website usage analytics to improve experience.',
      ],
      yourRightsItems: [
        'Access, correct, or delete your personal data.',
        'Opt-out of marketing communications anytime.',
        'Contact us for privacy-related questions.',
      ],
      contactText: 'For privacy inquiries, email us at',
    },
    terms: {
      title: 'Terms of Service',
      intro: 'Please review the terms governing your use of our site.',
      agreement: 'Agreement to Terms',
      useOfService: 'Use of the Service',
      limitation: 'Limitation of Liability',
      contact: 'Contact',
      useItems: [
        'Do not misuse or attempt to disrupt the site.',
        'Product details, pricing, shipping, and returns are subject to change.',
        'We may update these terms; continued use constitutes acceptance.',
      ],
      limitationText: 'To the fullest extent permitted by law, we are not liable for indirect or incidental damages arising from your use of the site.',
      contactText: 'Questions about these terms? Email',
    },
    defaults: {
      siteDescription: 'Discover premium products with exceptional quality and design',
      aboutText: "We're passionate about bringing you the finest products that combine quality, innovation, and style.",
      ourStory: "Founded with a vision to make premium products accessible to everyone, Your Brand has been dedicated to curating exceptional items that enhance your daily life. We believe that quality shouldn't be compromised, and every product in our collection reflects this commitment.",
      ourMission: 'To provide our customers with carefully selected, high-quality products that offer both functionality and style. We work directly with trusted manufacturers and suppliers to ensure that every item meets our rigorous standards.',
      whyChooseUs: [
        'Rigorous quality control and product testing',
        'Competitive pricing with transparent policies',
        'Excellent customer service and support',
        'Fast and reliable shipping',
        'Satisfaction guarantee on all products',
      ],
      privacyPolicy: 'We value your privacy. This policy explains what data we collect, how we use it, and your rights. We collect basic information needed to operate our services, never sell personal data, and provide ways to access, correct, or delete your information.',
      termsOfService: 'By using our site, you agree to our terms. This includes acceptable use, product information, pricing, shipping, returns, disclaimers, and limitations of liability. Please review carefully and contact us with any questions.',
    },
  },
  zh: {
    nav: {
      home: '首页',
      products: '产品',
      about: '关于我们',
      contact: '联系我们',
      allProducts: '全部产品',
      browseByCategory: '按分类浏览',
      searchProducts: '搜索产品',
      search: '搜索',
      cart: '购物车',
    },
    footer: {
      navigation: '导航',
      legal: '法律条款',
      followUs: '关注我们',
      privacyPolicy: '隐私政策',
      termsOfService: '服务条款',
      loading: '加载中...',
    },
    common: {
      viewDetails: '查看详情',
      buyOnAmazon: '前往亚马逊购买',
      addToCart: '加入购物车',
      addedToCart: '已加入购物车',
      quantity: '数量',
      decreaseQuantity: '减少数量',
      increaseQuantity: '增加数量',
      close: '关闭',
    },
    home: {
      featuredTitle: '精选产品',
      featuredSubtitle: '甄选高品质产品，兼具卓越品质与设计感。',
      whyChooseTitle: '为何选择我们',
      whyChooseSubtitle: '我们以高标准品质、创新设计与以客户为中心的服务重新定义购物体验。',
      feature1Title: '卓越品质',
      feature1Description: '每件产品都经过严格品质检测，确保达到高标准。',
      feature2Title: '安全可信',
      feature2Description: '先进安全措施保护您的数据，提供企业级加密与隐私保障。',
      feature3Title: '极速配送',
      feature3Description: '高效配送网络让您的订单快速且完好送达。',
      noFeaturedProducts: '暂无精选产品',
      viewAllProducts: '查看全部产品',
    },
    products: {
      title: '产品列表',
      subtitle: '探索我们精心挑选的优质产品，每件都兼具品质与价值。',
      allCategories: '全部分类',
      apply: '应用',
      emptyTitle: '当前暂无可用产品。',
      emptySubtitle: '请稍后查看新品上架。',
      productImage: '产品图片',
      untitledProduct: '未命名产品',
    },
    productDetail: {
      category: '分类',
      brand: '品牌',
      upc: 'UPC',
      dateFirstAvailable: '首次上架日期',
      availableOptions: '可选规格',
      productDescription: '产品描述',
      customerReviews: '用户评价',
      onlyReviewsWithImages: '仅显示带图片的评价',
      sort: '排序',
      newest: '最新',
      highestRating: '评分最高',
      notFound: '未找到产品',
      backToProducts: '返回产品列表',
    },
    cart: {
      title: '购物车',
      empty: '购物车为空。',
      browseProducts: '浏览产品',
      quantity: '数量',
      options: '选项',
      remove: '移除',
      total: '合计',
      continueShopping: '继续购物',
      clearCart: '清空购物车',
    },
    contact: {
      title: '联系我们',
      heroText: '有问题或建议？欢迎联系我们，我们会尽快回复。',
      sendMessage: '发送留言',
      sendMessageDesc: '填写下方表单，我们会尽快联系您。',
      fullName: '姓名',
      emailAddress: '邮箱',
      subject: '主题',
      country: '国家/地区',
      orderNo: '订单号',
      message: '留言内容',
      sending: '发送中...',
      send: '发送消息',
      success: '感谢您的留言！我们会尽快回复您。',
      error: '发送失败，请稍后再试。',
      getInTouch: '保持联系',
      getInTouchDesc: '我们随时为您答疑解惑。',
      email: '邮箱',
      phone: '电话',
      address: '地址',
      emailRequired: '邮箱为必填项',
      emailInvalid: '邮箱格式不正确，请输入有效邮箱地址（例如 user@example.com）',
    },
    about: {
      title: '关于我们',
      ourStory: '我们的故事',
      ourMission: '我们的使命',
      whyChooseUs: '选择我们的理由',
    },
    privacy: {
      title: '隐私政策',
      intro: '了解我们如何收集、使用并保护您的数据。',
      overview: '概览',
      dataWeCollect: '我们收集的数据',
      yourRights: '您的权利',
      contact: '联系方式',
      dataWeCollectItems: [
        '账户信息，例如姓名与邮箱。',
        '订单与付款信息（安全处理）。',
        '网站使用分析数据，用于优化体验。',
      ],
      yourRightsItems: [
        '访问、更正或删除您的个人数据。',
        '随时取消营销通讯订阅。',
        '隐私相关问题可联系我们。',
      ],
      contactText: '隐私相关咨询，请邮件联系',
    },
    terms: {
      title: '服务条款',
      intro: '请阅读并了解使用本网站的相关条款。',
      agreement: '条款同意',
      useOfService: '服务使用',
      limitation: '责任限制',
      contact: '联系方式',
      useItems: [
        '请勿滥用或破坏网站服务。',
        '产品信息、价格、物流与退换政策可能调整。',
        '条款更新后继续使用视为接受。',
      ],
      limitationText: '在法律允许的最大范围内，我们不承担因使用网站产生的间接或附带损失。',
      contactText: '如有疑问，请发送邮件至',
    },
    defaults: {
      siteDescription: '发现兼具卓越品质与设计感的优质产品',
      aboutText: '我们致力于提供兼具品质、创新与风格的优质产品。',
      ourStory: '我们以让高品质产品更易获得为愿景，持续甄选能提升日常生活品质的优质产品。我们相信品质不应妥协，每一件产品都体现这一承诺。',
      ourMission: '为客户提供精选的高品质产品，兼具功能性与设计感。我们与可信赖的制造商和供应商合作，确保每件产品符合严格标准。',
      whyChooseUs: [
        '严格的质量控制与产品测试',
        '透明政策下的有竞争力价格',
        '出色的客户服务与支持',
        '快速可靠的配送',
        '满意保障',
      ],
      privacyPolicy: '我们重视您的隐私。本政策说明我们收集的数据类型、使用方式以及您的权利。我们仅收集运营所需的基础信息，不会出售个人数据，并提供访问、更正与删除信息的方式。',
      termsOfService: '使用本站即表示您同意我们的条款，包括可接受的使用方式、产品信息、定价、运输、退换、免责声明与责任限制。如有疑问请联系我们。',
    },
  },
  ja: {
    nav: {
      home: 'ホーム',
      products: '商品一覧',
      about: '私たちについて',
      contact: 'お問い合わせ',
      allProducts: 'すべての商品',
      browseByCategory: 'カテゴリーから探す',
      searchProducts: '商品を検索',
      search: '検索',
      cart: 'カート',
    },
    footer: {
      navigation: 'ナビゲーション',
      legal: '法的情報',
      followUs: 'フォローする',
      privacyPolicy: 'プライバシーポリシー',
      termsOfService: '利用規約',
      loading: '読み込み中...',
    },
    common: {
      viewDetails: '詳細を見る',
      buyOnAmazon: 'Amazonで購入',
      addToCart: 'カートに追加',
      addedToCart: 'カートに追加しました',
      quantity: '数量',
      decreaseQuantity: '数量を減らす',
      increaseQuantity: '数量を増やす',
      close: '閉じる',
    },
    home: {
      featuredTitle: '注目商品',
      featuredSubtitle: '厳選された高品質な商品コレクションをご覧ください。',
      whyChooseTitle: '選ばれる理由',
      whyChooseSubtitle: '妥協のない品質、革新的なデザイン、顧客第一の姿勢で新しい体験を提供します。',
      feature1Title: 'プレミアム品質',
      feature1Description: 'すべての商品は厳格な品質テストを経ています。',
      feature2Title: '安全・信頼',
      feature2Description: '高度なセキュリティでデータを保護します。',
      feature3Title: '迅速な配送',
      feature3Description: '最適化された配送ネットワークで素早くお届け。',
      noFeaturedProducts: '注目商品はありません',
      viewAllProducts: 'すべての商品を見る',
    },
    products: {
      title: '商品一覧',
      subtitle: '品質と価値にこだわった商品を厳選しています。',
      allCategories: 'すべてのカテゴリー',
      apply: '適用',
      emptyTitle: '現在商品がありません。',
      emptySubtitle: '新着入荷をお待ちください。',
      productImage: '商品画像',
      untitledProduct: '無題の商品',
    },
    productDetail: {
      category: 'カテゴリー',
      brand: 'ブランド',
      upc: 'UPC',
      dateFirstAvailable: '販売開始日',
      availableOptions: '選択肢',
      productDescription: '商品説明',
      customerReviews: 'カスタマーレビュー',
      onlyReviewsWithImages: '画像付きレビューのみ',
      sort: '並び替え',
      newest: '新着順',
      highestRating: '高評価順',
      notFound: '商品が見つかりません',
      backToProducts: '商品一覧に戻る',
    },
    cart: {
      title: 'カート',
      empty: 'カートは空です。',
      browseProducts: '商品を見る',
      quantity: '数量',
      options: 'オプション',
      remove: '削除',
      total: '合計',
      continueShopping: '買い物を続ける',
      clearCart: 'カートを空にする',
    },
    contact: {
      title: 'お問い合わせ',
      heroText: 'ご質問やご意見があればお気軽にご連絡ください。できるだけ早く返信いたします。',
      sendMessage: 'メッセージを送信',
      sendMessageDesc: '下記フォームにご入力ください。',
      fullName: 'お名前',
      emailAddress: 'メールアドレス',
      subject: '件名',
      country: '国',
      orderNo: '注文番号',
      message: '内容',
      sending: '送信中...',
      send: '送信',
      success: 'メッセージを受け付けました。近日中にご連絡します。',
      error: '送信中にエラーが発生しました。再度お試しください。',
      getInTouch: '連絡先',
      getInTouchDesc: 'ご質問があればお気軽にお問い合わせください。',
      email: 'メール',
      phone: '電話',
      address: '住所',
      emailRequired: 'メールアドレスは必須です',
      emailInvalid: 'メールアドレスの形式が正しくありません（例: user@example.com）',
    },
    about: {
      title: '私たちについて',
      ourStory: '私たちのストーリー',
      ourMission: '私たちの使命',
      whyChooseUs: '選ばれる理由',
    },
    privacy: {
      title: 'プライバシーポリシー',
      intro: 'データの収集、利用、保護についてご案内します。',
      overview: '概要',
      dataWeCollect: '収集するデータ',
      yourRights: 'お客様の権利',
      contact: 'お問い合わせ',
      dataWeCollectItems: [
        '氏名やメールアドレスなどのアカウント情報。',
        '安全に処理される注文・支払い情報。',
        '体験向上のためのサイト利用分析。',
      ],
      yourRightsItems: [
        '個人データの閲覧、修正、削除。',
        'マーケティング配信の停止。',
        'プライバシーに関するお問い合わせ。',
      ],
      contactText: 'プライバシーに関するお問い合わせは',
    },
    terms: {
      title: '利用規約',
      intro: 'サイト利用に関する規約をご確認ください。',
      agreement: '規約への同意',
      useOfService: 'サービスの利用',
      limitation: '責任の制限',
      contact: 'お問い合わせ',
      useItems: [
        'サイトの誤用や妨害行為は禁止です。',
        '商品情報、価格、配送、返品は変更される場合があります。',
        '規約の更新後の利用は同意とみなします。',
      ],
      limitationText: '法律で認められる範囲内で、当社は間接的または付随的な損害について責任を負いません。',
      contactText: '規約に関するお問い合わせは',
    },
    defaults: {
      siteDescription: '高品質でデザイン性に優れた商品をお届けします',
      aboutText: '品質・革新・スタイルを兼ね備えた商品をお届けします。',
      ourStory: '高品質な商品をより身近に届けるというビジョンのもと、日常を豊かにする商品を厳選しています。品質への妥協は許されないと考え、すべての商品にその想いが反映されています。',
      ourMission: '機能性とデザイン性を兼ね備えた高品質な商品を提供します。信頼できる製造・供給パートナーと連携し、厳格な基準を満たす商品をお届けします。',
      whyChooseUs: [
        '厳格な品質管理とテスト',
        '透明な価格設定',
        '優れたカスタマーサポート',
        '迅速で信頼できる配送',
        '満足保証',
      ],
      privacyPolicy: '当社はお客様のプライバシーを重視します。本ポリシーでは収集するデータ、利用方法、権利について説明します。必要最低限の情報のみを収集し、個人情報を販売することはありません。',
      termsOfService: '本サイトの利用により規約に同意したものとします。利用条件、商品情報、価格、配送、返品、免責事項、責任制限が含まれます。',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      products: 'Productos',
      about: 'Acerca de',
      contact: 'Contacto',
      allProducts: 'Todos los productos',
      browseByCategory: 'Explorar por categoría',
      searchProducts: 'Buscar productos',
      search: 'Buscar',
      cart: 'Carrito',
    },
    footer: {
      navigation: 'Navegación',
      legal: 'Legal',
      followUs: 'Síguenos',
      privacyPolicy: 'Política de privacidad',
      termsOfService: 'Términos de servicio',
      loading: 'Cargando...',
    },
    common: {
      viewDetails: 'Ver detalles',
      buyOnAmazon: 'Comprar en Amazon',
      addToCart: 'Agregar al carrito',
      addedToCart: 'Agregado al carrito',
      quantity: 'Cantidad',
      decreaseQuantity: 'Disminuir cantidad',
      increaseQuantity: 'Aumentar cantidad',
      close: 'Cerrar',
    },
    home: {
      featuredTitle: 'Productos destacados',
      featuredSubtitle: 'Descubre nuestra selección de productos premium de alta calidad y diseño.',
      whyChooseTitle: 'Por qué elegirnos',
      whyChooseSubtitle: 'Calidad sin concesiones, diseño innovador y enfoque en el cliente.',
      feature1Title: 'Calidad premium',
      feature1Description: 'Cada producto pasa por pruebas rigurosas de calidad.',
      feature2Title: 'Seguro y confiable',
      feature2Description: 'Medidas de seguridad avanzadas protegen tus datos.',
      feature3Title: 'Entrega rápida',
      feature3Description: 'Red logística optimizada para entregas rápidas.',
      noFeaturedProducts: 'No hay productos destacados',
      viewAllProducts: 'Ver todos los productos',
    },
    products: {
      title: 'Nuestros productos',
      subtitle: 'Explora nuestra colección cuidadosamente seleccionada de productos de calidad.',
      allCategories: 'Todas las categorías',
      apply: 'Aplicar',
      emptyTitle: 'No hay productos disponibles en este momento.',
      emptySubtitle: 'Vuelve pronto para ver nuevas llegadas.',
      productImage: 'Imagen del producto',
      untitledProduct: 'Producto sin título',
    },
    productDetail: {
      category: 'Categoría',
      brand: 'Marca',
      upc: 'UPC',
      dateFirstAvailable: 'Fecha de disponibilidad',
      availableOptions: 'Opciones disponibles',
      productDescription: 'Descripción del producto',
      customerReviews: 'Reseñas de clientes',
      onlyReviewsWithImages: 'Solo reseñas con imágenes',
      sort: 'Ordenar',
      newest: 'Más recientes',
      highestRating: 'Mejor calificación',
      notFound: 'Producto no encontrado',
      backToProducts: 'Volver a productos',
    },
    cart: {
      title: 'Carrito',
      empty: 'Tu carrito está vacío.',
      browseProducts: 'Ver productos',
      quantity: 'Cantidad',
      options: 'Opciones',
      remove: 'Eliminar',
      total: 'Total',
      continueShopping: 'Seguir comprando',
      clearCart: 'Vaciar carrito',
    },
    contact: {
      title: 'Contáctanos',
      heroText: '¿Tienes preguntas o comentarios? Envíanos un mensaje y responderemos pronto.',
      sendMessage: 'Enviar un mensaje',
      sendMessageDesc: 'Completa el formulario y te responderemos lo antes posible.',
      fullName: 'Nombre completo',
      emailAddress: 'Correo electrónico',
      subject: 'Asunto',
      country: 'País',
      orderNo: 'N.º de pedido',
      message: 'Mensaje',
      sending: 'Enviando...',
      send: 'Enviar mensaje',
      success: 'Gracias por tu mensaje. Te responderemos pronto.',
      error: 'Hubo un error al enviar tu mensaje. Inténtalo de nuevo.',
      getInTouch: 'Ponte en contacto',
      getInTouchDesc: 'Estamos aquí para ayudarte.',
      email: 'Correo',
      phone: 'Teléfono',
      address: 'Dirección',
      emailRequired: 'El correo es obligatorio',
      emailInvalid: 'Formato de correo inválido (ejemplo: user@example.com)',
    },
    about: {
      title: 'Acerca de',
      ourStory: 'Nuestra historia',
      ourMission: 'Nuestra misión',
      whyChooseUs: 'Por qué elegirnos',
    },
    privacy: {
      title: 'Política de privacidad',
      intro: 'Conoce cómo recopilamos, usamos y protegemos tus datos.',
      overview: 'Resumen',
      dataWeCollect: 'Datos que recopilamos',
      yourRights: 'Tus derechos',
      contact: 'Contacto',
      dataWeCollectItems: [
        'Información de cuenta como nombre y correo.',
        'Detalles de pedidos y pagos procesados de forma segura.',
        'Análisis de uso del sitio para mejorar la experiencia.',
      ],
      yourRightsItems: [
        'Acceder, corregir o eliminar tus datos personales.',
        'Cancelar comunicaciones de marketing en cualquier momento.',
        'Contactarnos por temas de privacidad.',
      ],
      contactText: 'Para consultas de privacidad, escríbenos a',
    },
    terms: {
      title: 'Términos de servicio',
      intro: 'Revisa los términos que rigen el uso del sitio.',
      agreement: 'Acuerdo de términos',
      useOfService: 'Uso del servicio',
      limitation: 'Limitación de responsabilidad',
      contact: 'Contacto',
      useItems: [
        'No hagas un uso indebido ni intentes interrumpir el sitio.',
        'Los detalles de productos, precios, envíos y devoluciones pueden cambiar.',
        'Podemos actualizar estos términos; el uso continuo implica aceptación.',
      ],
      limitationText: 'En la medida permitida por la ley, no somos responsables de daños indirectos o incidentales.',
      contactText: '¿Dudas sobre estos términos? Escríbenos a',
    },
    defaults: {
      siteDescription: 'Descubre productos premium con calidad y diseño excepcionales',
      aboutText: 'Nos apasiona ofrecerte productos que combinan calidad, innovación y estilo.',
      ourStory: 'Nacimos con la visión de hacer accesibles productos premium. Seleccionamos artículos excepcionales que mejoran tu día a día, sin comprometer la calidad.',
      ourMission: 'Ofrecer productos de alta calidad con funcionalidad y estilo, trabajando con fabricantes y proveedores confiables.',
      whyChooseUs: [
        'Control de calidad riguroso',
        'Precios competitivos y transparentes',
        'Excelente atención al cliente',
        'Envío rápido y confiable',
        'Garantía de satisfacción',
      ],
      privacyPolicy: 'Valoramos tu privacidad. Esta política explica qué datos recopilamos, cómo los usamos y tus derechos. Solo recopilamos información necesaria para operar y no vendemos datos personales.',
      termsOfService: 'Al usar el sitio aceptas nuestros términos, incluyendo uso aceptable, información de productos, precios, envíos, devoluciones y limitación de responsabilidad.',
    },
  },
  fr: {
    nav: {
      home: 'Accueil',
      products: 'Produits',
      about: 'À propos',
      contact: 'Contact',
      allProducts: 'Tous les produits',
      browseByCategory: 'Par catégorie',
      searchProducts: 'Rechercher des produits',
      search: 'Rechercher',
      cart: 'Panier',
    },
    footer: {
      navigation: 'Navigation',
      legal: 'Mentions légales',
      followUs: 'Suivez-nous',
      privacyPolicy: 'Politique de confidentialité',
      termsOfService: 'Conditions d’utilisation',
      loading: 'Chargement...',
    },
    common: {
      viewDetails: 'Voir les détails',
      buyOnAmazon: 'Acheter sur Amazon',
      addToCart: 'Ajouter au panier',
      addedToCart: 'Ajouté au panier',
      quantity: 'Quantité',
      decreaseQuantity: 'Diminuer la quantité',
      increaseQuantity: 'Augmenter la quantité',
      close: 'Fermer',
    },
    home: {
      featuredTitle: 'Produits en vedette',
      featuredSubtitle: 'Découvrez notre sélection premium de produits de qualité et au design soigné.',
      whyChooseTitle: 'Pourquoi nous choisir',
      whyChooseSubtitle: 'Qualité sans compromis, design innovant et priorité au client.',
      feature1Title: 'Qualité premium',
      feature1Description: 'Chaque produit est soumis à des tests de qualité stricts.',
      feature2Title: 'Sécurisé et fiable',
      feature2Description: 'Des mesures de sécurité avancées protègent vos données.',
      feature3Title: 'Livraison rapide',
      feature3Description: 'Un réseau optimisé pour des livraisons rapides.',
      noFeaturedProducts: 'Aucun produit en vedette',
      viewAllProducts: 'Voir tous les produits',
    },
    products: {
      title: 'Nos produits',
      subtitle: 'Découvrez notre collection soigneusement sélectionnée.',
      allCategories: 'Toutes les catégories',
      apply: 'Appliquer',
      emptyTitle: 'Aucun produit disponible pour le moment.',
      emptySubtitle: 'Revenez bientôt pour les nouveautés.',
      productImage: 'Image du produit',
      untitledProduct: 'Produit sans titre',
    },
    productDetail: {
      category: 'Catégorie',
      brand: 'Marque',
      upc: 'UPC',
      dateFirstAvailable: 'Date de disponibilité',
      availableOptions: 'Options disponibles',
      productDescription: 'Description du produit',
      customerReviews: 'Avis clients',
      onlyReviewsWithImages: 'Uniquement les avis avec images',
      sort: 'Trier',
      newest: 'Les plus récents',
      highestRating: 'Meilleures notes',
      notFound: 'Produit introuvable',
      backToProducts: 'Retour aux produits',
    },
    cart: {
      title: 'Panier',
      empty: 'Votre panier est vide.',
      browseProducts: 'Voir les produits',
      quantity: 'Quantité',
      options: 'Options',
      remove: 'Supprimer',
      total: 'Total',
      continueShopping: 'Continuer les achats',
      clearCart: 'Vider le panier',
    },
    contact: {
      title: 'Contactez-nous',
      heroText: 'Une question ou un commentaire ? Envoyez-nous un message, nous répondrons rapidement.',
      sendMessage: 'Envoyer un message',
      sendMessageDesc: 'Remplissez le formulaire et nous vous répondrons au plus vite.',
      fullName: 'Nom complet',
      emailAddress: 'Adresse e-mail',
      subject: 'Objet',
      country: 'Pays',
      orderNo: 'N° de commande',
      message: 'Message',
      sending: 'Envoi...',
      send: 'Envoyer le message',
      success: 'Merci pour votre message. Nous vous répondrons rapidement.',
      error: 'Une erreur est survenue lors de l’envoi. Veuillez réessayer.',
      getInTouch: 'Nous contacter',
      getInTouchDesc: 'Nous sommes là pour vous aider.',
      email: 'E-mail',
      phone: 'Téléphone',
      address: 'Adresse',
      emailRequired: 'L’e-mail est obligatoire',
      emailInvalid: 'Format d’e-mail invalide (ex: user@example.com)',
    },
    about: {
      title: 'À propos',
      ourStory: 'Notre histoire',
      ourMission: 'Notre mission',
      whyChooseUs: 'Pourquoi nous choisir',
    },
    privacy: {
      title: 'Politique de confidentialité',
      intro: 'Découvrez comment nous collectons, utilisons et protégeons vos données.',
      overview: 'Aperçu',
      dataWeCollect: 'Données collectées',
      yourRights: 'Vos droits',
      contact: 'Contact',
      dataWeCollectItems: [
        'Informations de compte comme nom et e-mail.',
        'Détails de commande et paiement traités en toute sécurité.',
        'Analyses d’usage du site pour améliorer l’expérience.',
      ],
      yourRightsItems: [
        'Accéder, corriger ou supprimer vos données personnelles.',
        'Vous désinscrire des communications marketing.',
        'Nous contacter pour toute question de confidentialité.',
      ],
      contactText: 'Pour toute question de confidentialité, écrivez-nous à',
    },
    terms: {
      title: 'Conditions d’utilisation',
      intro: 'Veuillez consulter les conditions d’utilisation du site.',
      agreement: 'Accord aux conditions',
      useOfService: 'Utilisation du service',
      limitation: 'Limitation de responsabilité',
      contact: 'Contact',
      useItems: [
        'Ne pas abuser ou perturber le site.',
        'Les informations produits, prix, livraison et retours peuvent changer.',
        'La poursuite de l’utilisation vaut acceptation.',
      ],
      limitationText: 'Dans la limite autorisée par la loi, nous ne sommes pas responsables des dommages indirects.',
      contactText: 'Des questions sur ces conditions ? Écrivez à',
    },
    defaults: {
      siteDescription: 'Découvrez des produits premium au design et à la qualité exceptionnels',
      aboutText: 'Nous sommes passionnés par des produits alliant qualité, innovation et style.',
      ourStory: 'Nous avons été fondés pour rendre les produits premium accessibles à tous, avec une sélection qui améliore le quotidien sans compromis sur la qualité.',
      ourMission: 'Fournir des produits soigneusement sélectionnés, alliant fonctionnalité et style, avec des partenaires de confiance.',
      whyChooseUs: [
        'Contrôle qualité rigoureux',
        'Prix compétitifs et transparents',
        'Service client excellent',
        'Livraison rapide et fiable',
        'Garantie de satisfaction',
      ],
      privacyPolicy: 'Nous respectons votre vie privée. Cette politique explique les données collectées, leur usage et vos droits. Nous ne vendons jamais vos données personnelles.',
      termsOfService: 'En utilisant le site, vous acceptez nos conditions, incluant l’usage acceptable, les informations produits, les prix, la livraison, les retours et les limitations de responsabilité.',
    },
  },
  de: {
    nav: {
      home: 'Startseite',
      products: 'Produkte',
      about: 'Über uns',
      contact: 'Kontakt',
      allProducts: 'Alle Produkte',
      browseByCategory: 'Nach Kategorie',
      searchProducts: 'Produkte suchen',
      search: 'Suchen',
      cart: 'Warenkorb',
    },
    footer: {
      navigation: 'Navigation',
      legal: 'Rechtliches',
      followUs: 'Folgen Sie uns',
      privacyPolicy: 'Datenschutzerklärung',
      termsOfService: 'Nutzungsbedingungen',
      loading: 'Wird geladen...',
    },
    common: {
      viewDetails: 'Details ansehen',
      buyOnAmazon: 'Bei Amazon kaufen',
      addToCart: 'In den Warenkorb',
      addedToCart: 'In den Warenkorb gelegt',
      quantity: 'Menge',
      decreaseQuantity: 'Menge verringern',
      increaseQuantity: 'Menge erhöhen',
      close: 'Schließen',
    },
    home: {
      featuredTitle: 'Empfohlene Produkte',
      featuredSubtitle: 'Entdecken Sie unsere sorgfältig kuratierte Auswahl hochwertiger Produkte.',
      whyChooseTitle: 'Warum uns wählen',
      whyChooseSubtitle: 'Kompromisslose Qualität, innovatives Design und kundenorientierter Service.',
      feature1Title: 'Premiumqualität',
      feature1Description: 'Jedes Produkt durchläuft strenge Qualitätsprüfungen.',
      feature2Title: 'Sicher & vertrauenswürdig',
      feature2Description: 'Moderne Sicherheitsmaßnahmen schützen Ihre Daten.',
      feature3Title: 'Schnelle Lieferung',
      feature3Description: 'Optimiertes Liefernetz für schnelle Zustellung.',
      noFeaturedProducts: 'Keine empfohlenen Produkte verfügbar',
      viewAllProducts: 'Alle Produkte ansehen',
    },
    products: {
      title: 'Unsere Produkte',
      subtitle: 'Entdecken Sie unsere sorgfältig ausgewählte Kollektion hochwertiger Produkte.',
      allCategories: 'Alle Kategorien',
      apply: 'Anwenden',
      emptyTitle: 'Derzeit sind keine Produkte verfügbar.',
      emptySubtitle: 'Bitte schauen Sie später wieder vorbei.',
      productImage: 'Produktbild',
      untitledProduct: 'Unbenanntes Produkt',
    },
    productDetail: {
      category: 'Kategorie',
      brand: 'Marke',
      upc: 'UPC',
      dateFirstAvailable: 'Erstverfügbarkeit',
      availableOptions: 'Verfügbare Optionen',
      productDescription: 'Produktbeschreibung',
      customerReviews: 'Kundenbewertungen',
      onlyReviewsWithImages: 'Nur Bewertungen mit Bildern',
      sort: 'Sortieren',
      newest: 'Neueste',
      highestRating: 'Beste Bewertung',
      notFound: 'Produkt nicht gefunden',
      backToProducts: 'Zurück zu den Produkten',
    },
    cart: {
      title: 'Warenkorb',
      empty: 'Ihr Warenkorb ist leer.',
      browseProducts: 'Produkte ansehen',
      quantity: 'Menge',
      options: 'Optionen',
      remove: 'Entfernen',
      total: 'Gesamt',
      continueShopping: 'Weiter einkaufen',
      clearCart: 'Warenkorb leeren',
    },
    contact: {
      title: 'Kontakt',
      heroText: 'Haben Sie Fragen oder Feedback? Schreiben Sie uns, wir antworten so schnell wie möglich.',
      sendMessage: 'Nachricht senden',
      sendMessageDesc: 'Füllen Sie das Formular aus, wir melden uns schnellstmöglich.',
      fullName: 'Vollständiger Name',
      emailAddress: 'E-Mail-Adresse',
      subject: 'Betreff',
      country: 'Land',
      orderNo: 'Bestellnr.',
      message: 'Nachricht',
      sending: 'Wird gesendet...',
      send: 'Nachricht senden',
      success: 'Vielen Dank! Wir melden uns bald.',
      error: 'Beim Senden ist ein Fehler aufgetreten. Bitte erneut versuchen.',
      getInTouch: 'Kontakt aufnehmen',
      getInTouchDesc: 'Wir helfen Ihnen gerne weiter.',
      email: 'E-Mail',
      phone: 'Telefon',
      address: 'Adresse',
      emailRequired: 'E-Mail ist erforderlich',
      emailInvalid: 'Ungültiges E-Mail-Format (z. B. user@example.com)',
    },
    about: {
      title: 'Über uns',
      ourStory: 'Unsere Geschichte',
      ourMission: 'Unsere Mission',
      whyChooseUs: 'Warum uns wählen',
    },
    privacy: {
      title: 'Datenschutzerklärung',
      intro: 'Erfahren Sie, wie wir Daten sammeln, nutzen und schützen.',
      overview: 'Überblick',
      dataWeCollect: 'Erhobene Daten',
      yourRights: 'Ihre Rechte',
      contact: 'Kontakt',
      dataWeCollectItems: [
        'Kontoinformationen wie Name und E-Mail.',
        'Bestell- und Zahlungsdetails, sicher verarbeitet.',
        'Nutzungsanalysen zur Verbesserung der Erfahrung.',
      ],
      yourRightsItems: [
        'Zugriff, Korrektur oder Löschung Ihrer Daten.',
        'Abmeldung von Marketing-Kommunikation.',
        'Kontakt bei Datenschutzfragen.',
      ],
      contactText: 'Bei Datenschutzanfragen schreiben Sie an',
    },
    terms: {
      title: 'Nutzungsbedingungen',
      intro: 'Bitte lesen Sie die Bedingungen für die Nutzung unserer Website.',
      agreement: 'Zustimmung zu den Bedingungen',
      useOfService: 'Nutzung des Dienstes',
      limitation: 'Haftungsbeschränkung',
      contact: 'Kontakt',
      useItems: [
        'Die Website darf nicht missbraucht oder gestört werden.',
        'Produktdetails, Preise, Versand und Rückgabe können sich ändern.',
        'Aktualisierte Bedingungen gelten durch fortgesetzte Nutzung.',
      ],
      limitationText: 'Soweit gesetzlich zulässig, haften wir nicht für indirekte oder beiläufige Schäden.',
      contactText: 'Fragen zu diesen Bedingungen? Schreiben Sie an',
    },
    defaults: {
      siteDescription: 'Entdecken Sie Premiumprodukte mit außergewöhnlicher Qualität und Design',
      aboutText: 'Wir sind leidenschaftlich dabei, Produkte mit Qualität, Innovation und Stil anzubieten.',
      ourStory: 'Mit der Vision, Premiumprodukte für alle zugänglich zu machen, kuratieren wir außergewöhnliche Artikel, die den Alltag verbessern.',
      ourMission: 'Wir bieten sorgfältig ausgewählte, hochwertige Produkte mit Funktionalität und Stil an und arbeiten mit vertrauenswürdigen Partnern.',
      whyChooseUs: [
        'Strenge Qualitätskontrolle',
        'Wettbewerbsfähige, transparente Preise',
        'Exzellenter Kundenservice',
        'Schneller, zuverlässiger Versand',
        'Zufriedenheitsgarantie',
      ],
      privacyPolicy: 'Wir schätzen Ihre Privatsphäre. Diese Richtlinie erklärt, welche Daten wir sammeln, wie wir sie nutzen und welche Rechte Sie haben.',
      termsOfService: 'Durch die Nutzung der Website stimmen Sie unseren Bedingungen zu, einschließlich akzeptabler Nutzung, Produktinformationen, Preisen, Versand und Haftungsbeschränkungen.',
    },
  },
  ko: {
    nav: {
      home: '홈',
      products: '상품',
      about: '소개',
      contact: '문의',
      allProducts: '전체 상품',
      browseByCategory: '카테고리별 보기',
      searchProducts: '상품 검색',
      search: '검색',
      cart: '장바구니',
    },
    footer: {
      navigation: '네비게이션',
      legal: '법적 고지',
      followUs: '팔로우',
      privacyPolicy: '개인정보 처리방침',
      termsOfService: '이용약관',
      loading: '로딩 중...',
    },
    common: {
      viewDetails: '자세히 보기',
      buyOnAmazon: '아마존에서 구매',
      addToCart: '장바구니 담기',
      addedToCart: '장바구니에 담겼습니다',
      quantity: '수량',
      decreaseQuantity: '수량 감소',
      increaseQuantity: '수량 증가',
      close: '닫기',
    },
    home: {
      featuredTitle: '추천 상품',
      featuredSubtitle: '품질과 디자인을 모두 갖춘 프리미엄 상품을 만나보세요.',
      whyChooseTitle: '왜 선택해야 하나요',
      whyChooseSubtitle: '타협 없는 품질, 혁신적인 디자인, 고객 중심 서비스를 제공합니다.',
      feature1Title: '프리미엄 품질',
      feature1Description: '모든 상품은 엄격한 품질 검사를 거칩니다.',
      feature2Title: '안전하고 신뢰할 수 있음',
      feature2Description: '고급 보안으로 데이터를 보호합니다.',
      feature3Title: '빠른 배송',
      feature3Description: '최적화된 배송 네트워크로 신속 배송.',
      noFeaturedProducts: '추천 상품이 없습니다',
      viewAllProducts: '전체 상품 보기',
    },
    products: {
      title: '상품 목록',
      subtitle: '엄선된 고품질 상품 컬렉션을 살펴보세요.',
      allCategories: '전체 카테고리',
      apply: '적용',
      emptyTitle: '현재 उपलब्ध한 상품이 없습니다.',
      emptySubtitle: '새 상품을 위해 다시 방문해 주세요.',
      productImage: '상품 이미지',
      untitledProduct: '이름 없는 상품',
    },
    productDetail: {
      category: '카테고리',
      brand: '브랜드',
      upc: 'UPC',
      dateFirstAvailable: '판매 시작일',
      availableOptions: '선택 옵션',
      productDescription: '상품 설명',
      customerReviews: '고객 리뷰',
      onlyReviewsWithImages: '이미지 포함 리뷰만',
      sort: '정렬',
      newest: '최신순',
      highestRating: '평점 높은 순',
      notFound: '상품을 찾을 수 없습니다',
      backToProducts: '상품 목록으로 돌아가기',
    },
    cart: {
      title: '장바구니',
      empty: '장바구니가 비어 있습니다.',
      browseProducts: '상품 보기',
      quantity: '수량',
      options: '옵션',
      remove: '삭제',
      total: '합계',
      continueShopping: '쇼핑 계속하기',
      clearCart: '장바구니 비우기',
    },
    contact: {
      title: '문의하기',
      heroText: '문의 사항이 있으신가요? 메시지를 보내주시면 빠르게 답변드립니다.',
      sendMessage: '메시지 보내기',
      sendMessageDesc: '아래 양식을 작성해 주세요.',
      fullName: '이름',
      emailAddress: '이메일',
      subject: '제목',
      country: '국가',
      orderNo: '주문 번호',
      message: '메시지',
      sending: '전송 중...',
      send: '메시지 보내기',
      success: '메시지가 접수되었습니다. 곧 답변드리겠습니다.',
      error: '메시지 전송에 실패했습니다. 다시 시도해 주세요.',
      getInTouch: '연락처',
      getInTouchDesc: '궁금한 점이 있으면 언제든지 문의해 주세요.',
      email: '이메일',
      phone: '전화',
      address: '주소',
      emailRequired: '이메일은 필수입니다',
      emailInvalid: '이메일 형식이 올바르지 않습니다 (예: user@example.com)',
    },
    about: {
      title: '회사 소개',
      ourStory: '우리의 이야기',
      ourMission: '우리의 미션',
      whyChooseUs: '선택해야 하는 이유',
    },
    privacy: {
      title: '개인정보 처리방침',
      intro: '데이터 수집, 사용, 보호 방법을 안내합니다.',
      overview: '개요',
      dataWeCollect: '수집하는 데이터',
      yourRights: '권리',
      contact: '문의',
      dataWeCollectItems: [
        '이름과 이메일 등 계정 정보.',
        '안전하게 처리되는 주문 및 결제 정보.',
        '사용 경험 개선을 위한 사이트 분석.',
      ],
      yourRightsItems: [
        '개인 데이터 열람, 수정, 삭제.',
        '마케팅 수신 거부.',
        '개인정보 관련 문의.',
      ],
      contactText: '개인정보 관련 문의는',
    },
    terms: {
      title: '이용약관',
      intro: '사이트 이용에 관한 약관을 확인해 주세요.',
      agreement: '약관 동의',
      useOfService: '서비스 이용',
      limitation: '책임 제한',
      contact: '문의',
      useItems: [
        '사이트를 부정 사용하거나 방해하지 마세요.',
        '상품 정보, 가격, 배송, 반품은 변경될 수 있습니다.',
        '약관이 변경될 수 있으며, 계속 이용 시 동의로 간주됩니다.',
      ],
      limitationText: '법이 허용하는 범위 내에서 당사는 간접적 손해에 책임을 지지 않습니다.',
      contactText: '약관 관련 문의는',
    },
    defaults: {
      siteDescription: '탁월한 품질과 디자인의 프리미엄 상품을 만나보세요',
      aboutText: '품질, 혁신, 스타일을 겸비한 상품을 제공합니다.',
      ourStory: '프리미엄 상품을 모두가 쉽게 접할 수 있도록 한다는 비전으로 시작했습니다. 일상을 더 풍요롭게 하는 상품을 엄선합니다.',
      ourMission: '기능성과 스타일을 갖춘 고품질 상품을 제공하며, 신뢰할 수 있는 파트너와 협력합니다.',
      whyChooseUs: [
        '엄격한 품질 관리',
        '투명한 가격 정책',
        '우수한 고객 지원',
        '빠르고 신뢰할 수 있는 배송',
        '만족 보장',
      ],
      privacyPolicy: '당사는 개인정보를 소중히 여깁니다. 본 정책은 수집하는 데이터, 사용 방법, 권리를 설명합니다.',
      termsOfService: '사이트 이용 시 이용약관에 동의한 것으로 간주되며, 이용 조건과 책임 제한이 포함됩니다.',
    },
  },
} as const

export type SupportedLanguage = keyof typeof translations
export type Translations = (typeof translations)['en']

export function normalizeLanguage(value?: string): SupportedLanguage {
  const raw = (value || '').toLowerCase()
  if (raw.startsWith('zh')) return 'zh'
  if (raw.startsWith('ja')) return 'ja'
  if (raw.startsWith('es')) return 'es'
  if (raw.startsWith('fr')) return 'fr'
  if (raw.startsWith('de')) return 'de'
  if (raw.startsWith('ko')) return 'ko'
  return 'en'
}

export function getTranslations(value?: string): Translations {
  return translations[normalizeLanguage(value)] as Translations
}

export function getLocale(value?: string): string {
  const lang = normalizeLanguage(value)
  if (lang === 'zh') return 'zh-CN'
  if (lang === 'ja') return 'ja-JP'
  if (lang === 'es') return 'es-ES'
  if (lang === 'fr') return 'fr-FR'
  if (lang === 'de') return 'de-DE'
  if (lang === 'ko') return 'ko-KR'
  return 'en-US'
}

export function resolveContent(value: string | undefined, key: keyof Translations['defaults'], language?: string): string {
  const t = getTranslations(language)
  const base = translations.en.defaults[key]
  const next = t.defaults[key]
  if (Array.isArray(base) || Array.isArray(next)) {
    const baseJoined = Array.isArray(base) ? base.join('\n') : String(base)
    if (!value || value.trim() === '' || value === baseJoined) {
      return Array.isArray(next) ? next.join('\n') : String(next)
    }
    return value
  }
  if (!value || value.trim() === '' || value === base) {
    return String(next)
  }
  return value
}

export function resolveContentList(value: string | undefined, language?: string): string[] {
  const base = translations.en.defaults.whyChooseUs.join('\n')
  if (!value || value.trim() === '' || value === base) {
    return Array.from(getTranslations(language).defaults.whyChooseUs)
  }
  return value.split('\n').filter(item => item.trim()).map(item => item.trim())
}

export function formatPrice(price: number, locale: string = 'en-US', currency: string = 'USD'): string {
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency,
  }).format(price)
}

export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w ]+/g, '')
    .replace(/ +/g, '-')
}

export function parseJsonField<T>(field: string | null): T[] {
  if (!field) return [] as T[]
  try {
    return JSON.parse(field) as T[]
  } catch {
    return [] as T[]
  }
}
